### PR TITLE
ContextEngineID and contextName in v3 traps

### PR DESCRIPTION
**Pull request by mrinaldas**
Added a constructor to add EngineId(ContextEngineId) and ContextName in v3 trap message.

Same changes in pull request created by KristianVirkus:configurable-engine. The pull request was created on older version of the code, the library code have moved on quite a lot since then and the engine/pipeline code have even been split which make the PR merge cumbersome. Therefore created a PR with same changes plus resolving unit tests based on latest master branch.

Separate PR with relevant changes have been created for samples project as well.

### CODE REVIEW

**Comment by mrinaldas** [comment]
Hi @lextm, Can this pull request be merged please? Thanks.

**Comment by lextm** [comment]
Found a few more issues with this pull request. Will investigate further and decide what else is needed.

**Comment by mrinaldas** [comment]
Thank you.

**Comment by lextm** [comment]
I cherry picked your commit that added the new constructor and also made some further changes in da4a39f430715af862435889dbee227ace4bef17. In that way there is no need to change the test cases and also match what `snmptrap` requires (both engine ID and context engine ID are now configurable).

Therefore, this pull request is no longer needed.

Thanks for your contribution.

**Comment by mrinaldas** [comment]
That's brilliant. Thank you so much. Appreciate your time and for accepting the changes. Appreciate your brilliant work with the snmp library. Cheers.

**Pull request closed without merging**
