### PR TITLE
Fixed the characters in the test were garbled.

### PR DESCRIPTION
**Pull request by geforce-hisa0904**
Change the char encoding to UTF-8

### CODE REVIEW

**Comment by geforce-hisa0904** [comment]
Hi @lextm,

I had merged master branch you committed in fd5f16865138294e45ef6850551b9b59edb47da2 into feature branch.
Therefore, it can build successfully.
Could  you check the source code if you have time?

**Comment by lextm** [comment]
I was hoping that you can do a rebase.

**Comment by geforce-hisa0904** [comment]
OK. I was rebase feature branch with force.

**Comment by lextm** [comment]
Thanks. Merged.

**Pull request merged**
